[package]
name = "taskmanager"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
serde_json = "1.0.104"
serde = { version="1.0.188", features=["derive"] }